[2024-10-14T09:14:47.169+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T09:14:47.181+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T09:14:45.939135+00:00 [queued]>
[2024-10-14T09:14:47.185+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T09:14:45.939135+00:00 [queued]>
[2024-10-14T09:14:47.186+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-14T09:14:47.192+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): spark_count_number_of_accidents> on 2024-10-14 09:14:45.939135+00:00
[2024-10-14T09:14:47.196+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2384) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T09:14:47.196+0000] {standard_task_runner.py:72} INFO - Started process 2386 to run task
[2024-10-14T09:14:47.197+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'count_accidents', 'spark_count_number_of_accidents', 'manual__2024-10-14T09:14:45.939135+00:00', '--job-id', '333', '--raw', '--subdir', 'DAGS_FOLDER/count_accidents_dag.py', '--cfg-path', '/tmp/tmpe9gk083g']
[2024-10-14T09:14:47.198+0000] {standard_task_runner.py:105} INFO - Job 333: Subtask spark_count_number_of_accidents
[2024-10-14T09:14:47.228+0000] {task_command.py:467} INFO - Running <TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T09:14:45.939135+00:00 [running]> on host 14eb9bd36bc1
[2024-10-14T09:14:47.279+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_accidents' AIRFLOW_CTX_TASK_ID='spark_count_number_of_accidents' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T09:14:45.939135+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-14T09:14:45.939135+00:00'
[2024-10-14T09:14:47.281+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T09:14:47.281+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T09:14:47.282+0000] {logging_mixin.py:190} INFO - Current task name:spark_count_number_of_accidents state:running start_date:2024-10-14 09:14:47.181869+00:00
[2024-10-14T09:14:47.282+0000] {logging_mixin.py:190} INFO - Dag name:count_accidents and current dag run status:running
[2024-10-14T09:14:47.282+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T09:14:47.289+0000] {base.py:84} INFO - Retrieving connection 'spark'
[2024-10-14T09:14:47.290+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://localhost:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py
[2024-10-14T09:14:48.834+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO SparkContext: Running Spark version 3.5.3
[2024-10-14T09:14:48.835+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO SparkContext: OS info Linux, 6.6.32-linuxkit, aarch64
[2024-10-14T09:14:48.835+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO SparkContext: Java version 17.0.12
[2024-10-14T09:14:48.862+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-14T09:14:48.904+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO ResourceUtils: ==============================================================
[2024-10-14T09:14:48.905+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-14T09:14:48.905+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO ResourceUtils: ==============================================================
[2024-10-14T09:14:48.905+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO SparkContext: Submitted application: CountAccidents
[2024-10-14T09:14:48.916+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-14T09:14:48.920+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO ResourceProfile: Limiting resource is cpu
[2024-10-14T09:14:48.920+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-14T09:14:48.944+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO SecurityManager: Changing view acls to: default
[2024-10-14T09:14:48.945+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO SecurityManager: Changing modify acls to: default
[2024-10-14T09:14:48.945+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO SecurityManager: Changing view acls groups to:
[2024-10-14T09:14:48.946+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO SecurityManager: Changing modify acls groups to:
[2024-10-14T09:14:48.946+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:48 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2024-10-14T09:14:49.059+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO Utils: Successfully started service 'sparkDriver' on port 41583.
[2024-10-14T09:14:49.074+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO SparkEnv: Registering MapOutputTracker
[2024-10-14T09:14:49.093+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-14T09:14:49.102+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-14T09:14:49.104+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-14T09:14:49.107+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-14T09:14:49.129+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-729ae203-d3c0-4a84-ab01-6411bcec8e14
[2024-10-14T09:14:49.137+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-14T09:14:49.146+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-14T09:14:49.212+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-14T09:14:49.255+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-14T09:14:49.325+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://localhost:7077...
[2024-10-14T09:14:49.349+0000] {spark_submit.py:571} INFO - 24/10/14 09:14:49 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master localhost:7077
[2024-10-14T09:14:49.350+0000] {spark_submit.py:571} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-10-14T09:14:49.350+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-10-14T09:14:49.350+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-10-14T09:14:49.350+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-10-14T09:14:49.350+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-10-14T09:14:49.350+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-10-14T09:14:49.351+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-10-14T09:14:49.351+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-10-14T09:14:49.351+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-10-14T09:14:49.351+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-10-14T09:14:49.351+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-10-14T09:14:49.351+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:14:49.351+0000] {spark_submit.py:571} INFO - Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:7077
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - ... 4 more
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:7077
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-10-14T09:14:49.352+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-10-14T09:14:49.353+0000] {spark_submit.py:571} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-10-14T09:14:49.353+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-10-14T09:14:49.353+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-10-14T09:14:49.353+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-10-14T09:14:49.353+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-10-14T09:14:49.353+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-10-14T09:14:49.353+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-10-14T09:14:49.353+0000] {spark_submit.py:571} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-10-14T09:14:49.353+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-10-14T09:14:49.353+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:15:09.333+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:09 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://localhost:7077...
[2024-10-14T09:15:09.342+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:09 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master localhost:7077
[2024-10-14T09:15:09.342+0000] {spark_submit.py:571} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-10-14T09:15:09.343+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-10-14T09:15:09.343+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-10-14T09:15:09.344+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-10-14T09:15:09.344+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-10-14T09:15:09.345+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-10-14T09:15:09.345+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-10-14T09:15:09.346+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-10-14T09:15:09.346+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-10-14T09:15:09.347+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-10-14T09:15:09.347+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-10-14T09:15:09.347+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:15:09.347+0000] {spark_submit.py:571} INFO - Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:7077
[2024-10-14T09:15:09.348+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-10-14T09:15:09.348+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-10-14T09:15:09.348+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-10-14T09:15:09.348+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-10-14T09:15:09.349+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-10-14T09:15:09.349+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-10-14T09:15:09.349+0000] {spark_submit.py:571} INFO - ... 4 more
[2024-10-14T09:15:09.349+0000] {spark_submit.py:571} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:7077
[2024-10-14T09:15:09.350+0000] {spark_submit.py:571} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-10-14T09:15:09.350+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-10-14T09:15:09.350+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-10-14T09:15:09.351+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-10-14T09:15:09.351+0000] {spark_submit.py:571} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-10-14T09:15:09.351+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-10-14T09:15:09.351+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-10-14T09:15:09.352+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-10-14T09:15:09.352+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-10-14T09:15:09.352+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-10-14T09:15:09.352+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-10-14T09:15:09.353+0000] {spark_submit.py:571} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-10-14T09:15:09.353+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-10-14T09:15:09.353+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:15:29.336+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:29 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://localhost:7077...
[2024-10-14T09:15:29.362+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:29 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master localhost:7077
[2024-10-14T09:15:29.366+0000] {spark_submit.py:571} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-10-14T09:15:29.368+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-10-14T09:15:29.369+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-10-14T09:15:29.370+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-10-14T09:15:29.370+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-10-14T09:15:29.372+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-10-14T09:15:29.373+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-10-14T09:15:29.373+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-10-14T09:15:29.373+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-10-14T09:15:29.374+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-10-14T09:15:29.374+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-10-14T09:15:29.374+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:15:29.375+0000] {spark_submit.py:571} INFO - Caused by: java.io.IOException: Failed to connect to localhost/127.0.0.1:7077
[2024-10-14T09:15:29.375+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-10-14T09:15:29.375+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-10-14T09:15:29.375+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-10-14T09:15:29.376+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-10-14T09:15:29.376+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-10-14T09:15:29.376+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-10-14T09:15:29.377+0000] {spark_submit.py:571} INFO - ... 4 more
[2024-10-14T09:15:29.377+0000] {spark_submit.py:571} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:7077
[2024-10-14T09:15:29.377+0000] {spark_submit.py:571} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-10-14T09:15:29.377+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-10-14T09:15:29.378+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-10-14T09:15:29.378+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-10-14T09:15:29.378+0000] {spark_submit.py:571} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-10-14T09:15:29.378+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-10-14T09:15:29.379+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-10-14T09:15:29.379+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-10-14T09:15:29.379+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-10-14T09:15:29.379+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-10-14T09:15:29.380+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-10-14T09:15:29.380+0000] {spark_submit.py:571} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-10-14T09:15:29.380+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-10-14T09:15:29.380+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:15:49.352+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2024-10-14T09:15:49.355+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2024-10-14T09:15:49.378+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 43507.
[2024-10-14T09:15:49.380+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO NettyBlockTransferService: Server created on 14eb9bd36bc1:43507
[2024-10-14T09:15:49.382+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-14T09:15:49.391+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 14eb9bd36bc1, 43507, None)
[2024-10-14T09:15:49.397+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO BlockManagerMasterEndpoint: Registering block manager 14eb9bd36bc1:43507 with 434.4 MiB RAM, BlockManagerId(driver, 14eb9bd36bc1, 43507, None)
[2024-10-14T09:15:49.399+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 14eb9bd36bc1, 43507, None)
[2024-10-14T09:15:49.400+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 14eb9bd36bc1, 43507, None)
[2024-10-14T09:15:49.506+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-14T09:15:49.638+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-14T09:15:49.644+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO SparkUI: Stopped Spark web UI at http://14eb9bd36bc1:4040
[2024-10-14T09:15:49.647+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-14T09:15:49.651+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-14T09:15:49.652+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-10-14T09:15:49.652+0000] {spark_submit.py:571} INFO - File "/opt/airflow/spark/count_accidents.py", line 19, in <module>
[2024-10-14T09:15:49.653+0000] {spark_submit.py:571} INFO - count_accidents()
[2024-10-14T09:15:49.654+0000] {spark_submit.py:571} INFO - File "/opt/airflow/spark/count_accidents.py", line 8, in count_accidents
[2024-10-14T09:15:49.655+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2024-10-14T09:15:49.656+0000] {spark_submit.py:571} INFO - spark = SparkSession.builder.appName("CountAccidents").getOrCreate()
[2024-10-14T09:15:49.657+0000] {spark_submit.py:571} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-14T09:15:49.657+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 500, in getOrCreate
[2024-10-14T09:15:49.657+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 589, in __init__
[2024-10-14T09:15:49.657+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1587, in __call__
[2024-10-14T09:15:49.658+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-10-14T09:15:49.658+0000] {spark_submit.py:571} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.sql.SparkSession.
[2024-10-14T09:15:49.658+0000] {spark_submit.py:571} INFO - : java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
[2024-10-14T09:15:49.658+0000] {spark_submit.py:571} INFO - This stopped SparkContext was created at:
[2024-10-14T09:15:49.659+0000] {spark_submit.py:571} INFO - 
[2024-10-14T09:15:49.659+0000] {spark_submit.py:571} INFO - org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-10-14T09:15:49.659+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-10-14T09:15:49.659+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-10-14T09:15:49.660+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-10-14T09:15:49.660+0000] {spark_submit.py:571} INFO - java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2024-10-14T09:15:49.660+0000] {spark_submit.py:571} INFO - java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2024-10-14T09:15:49.661+0000] {spark_submit.py:571} INFO - py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-10-14T09:15:49.661+0000] {spark_submit.py:571} INFO - py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-10-14T09:15:49.661+0000] {spark_submit.py:571} INFO - py4j.Gateway.invoke(Gateway.java:238)
[2024-10-14T09:15:49.662+0000] {spark_submit.py:571} INFO - py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-10-14T09:15:49.662+0000] {spark_submit.py:571} INFO - py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-10-14T09:15:49.662+0000] {spark_submit.py:571} INFO - py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-14T09:15:49.662+0000] {spark_submit.py:571} INFO - py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-14T09:15:49.662+0000] {spark_submit.py:571} INFO - java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:15:49.663+0000] {spark_submit.py:571} INFO - 
[2024-10-14T09:15:49.663+0000] {spark_submit.py:571} INFO - The currently active SparkContext was created at:
[2024-10-14T09:15:49.663+0000] {spark_submit.py:571} INFO - 
[2024-10-14T09:15:49.663+0000] {spark_submit.py:571} INFO - org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-10-14T09:15:49.663+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-10-14T09:15:49.664+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-10-14T09:15:49.664+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-10-14T09:15:49.664+0000] {spark_submit.py:571} INFO - java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2024-10-14T09:15:49.664+0000] {spark_submit.py:571} INFO - java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2024-10-14T09:15:49.664+0000] {spark_submit.py:571} INFO - py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-10-14T09:15:49.664+0000] {spark_submit.py:571} INFO - py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-10-14T09:15:49.665+0000] {spark_submit.py:571} INFO - py4j.Gateway.invoke(Gateway.java:238)
[2024-10-14T09:15:49.665+0000] {spark_submit.py:571} INFO - py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-10-14T09:15:49.665+0000] {spark_submit.py:571} INFO - py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-10-14T09:15:49.665+0000] {spark_submit.py:571} INFO - py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-14T09:15:49.665+0000] {spark_submit.py:571} INFO - py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-14T09:15:49.666+0000] {spark_submit.py:571} INFO - java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:15:49.666+0000] {spark_submit.py:571} INFO - 
[2024-10-14T09:15:49.666+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:122)
[2024-10-14T09:15:49.666+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.SparkSession.<init>(SparkSession.scala:113)
[2024-10-14T09:15:49.666+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.SparkSession.<init>(SparkSession.scala:106)
[2024-10-14T09:15:49.666+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-10-14T09:15:49.667+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-10-14T09:15:49.667+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-10-14T09:15:49.667+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2024-10-14T09:15:49.667+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2024-10-14T09:15:49.667+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-10-14T09:15:49.668+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-10-14T09:15:49.668+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2024-10-14T09:15:49.668+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-10-14T09:15:49.668+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-10-14T09:15:49.669+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-14T09:15:49.669+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-14T09:15:49.669+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:15:49.670+0000] {spark_submit.py:571} INFO - 
[2024-10-14T09:15:49.670+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-14T09:15:49.670+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO MemoryStore: MemoryStore cleared
[2024-10-14T09:15:49.670+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO BlockManager: BlockManager stopped
[2024-10-14T09:15:49.671+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-14T09:15:49.675+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-14T09:15:49.682+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO SparkContext: Successfully stopped SparkContext
[2024-10-14T09:15:49.706+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO ShutdownHookManager: Shutdown hook called
[2024-10-14T09:15:49.706+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-c6f1b065-87b5-4040-8d74-ff2fccbbb30b
[2024-10-14T09:15:49.709+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-c6f1b065-87b5-4040-8d74-ff2fccbbb30b/pyspark-cbfabc50-eab1-4d35-a889-35a9786a394b
[2024-10-14T09:15:49.711+0000] {spark_submit.py:571} INFO - 24/10/14 09:15:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-ec14a464-4414-4446-bf80-745bd2c0f68c
[2024-10-14T09:15:49.748+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://localhost:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.
[2024-10-14T09:15:49.752+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-14T09:15:49.753+0000] {logging_mixin.py:190} INFO - Task start:2024-10-14 09:14:47.181869+00:00 end:2024-10-14 09:15:49.751447+00:00 duration:62.569578
[2024-10-14T09:15:49.753+0000] {logging_mixin.py:190} INFO - Task:<Task(SparkSubmitOperator): spark_count_number_of_accidents> dag:<DAG: count_accidents> dagrun:<DagRun count_accidents @ 2024-10-14 09:14:45.939135+00:00: manual__2024-10-14T09:14:45.939135+00:00, state:running, queued_at: 2024-10-14 09:14:45.946789+00:00. externally triggered: True>
[2024-10-14T09:15:49.753+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot execute: spark-submit --master spark://localhost:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.
[2024-10-14T09:15:49.753+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=count_accidents, task_id=spark_count_number_of_accidents, run_id=manual__2024-10-14T09:14:45.939135+00:00, execution_date=20241014T091445, start_date=20241014T091447, end_date=20241014T091549
[2024-10-14T09:15:49.767+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T09:15:49.768+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 333 for task spark_count_number_of_accidents (Cannot execute: spark-submit --master spark://localhost:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.; 2386)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://localhost:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.
[2024-10-14T09:15:49.821+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T09:15:49.838+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T09:15:49.840+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
