[2024-10-14T08:59:09.723+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T08:59:09.735+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T08:59:08.221057+00:00 [queued]>
[2024-10-14T08:59:09.740+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T08:59:08.221057+00:00 [queued]>
[2024-10-14T08:59:09.740+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-14T08:59:09.746+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): spark_count_number_of_accidents> on 2024-10-14 08:59:08.221057+00:00
[2024-10-14T08:59:09.750+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1583) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T08:59:09.751+0000] {standard_task_runner.py:72} INFO - Started process 1585 to run task
[2024-10-14T08:59:09.752+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'count_accidents', 'spark_count_number_of_accidents', 'manual__2024-10-14T08:59:08.221057+00:00', '--job-id', '328', '--raw', '--subdir', 'DAGS_FOLDER/count_accidents_dag.py', '--cfg-path', '/tmp/tmp4cuu0388']
[2024-10-14T08:59:09.753+0000] {standard_task_runner.py:105} INFO - Job 328: Subtask spark_count_number_of_accidents
[2024-10-14T08:59:09.798+0000] {task_command.py:467} INFO - Running <TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T08:59:08.221057+00:00 [running]> on host 14eb9bd36bc1
[2024-10-14T08:59:09.854+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_accidents' AIRFLOW_CTX_TASK_ID='spark_count_number_of_accidents' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T08:59:08.221057+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-14T08:59:08.221057+00:00'
[2024-10-14T08:59:09.855+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T08:59:09.856+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T08:59:09.856+0000] {logging_mixin.py:190} INFO - Current task name:spark_count_number_of_accidents state:running start_date:2024-10-14 08:59:09.736071+00:00
[2024-10-14T08:59:09.856+0000] {logging_mixin.py:190} INFO - Dag name:count_accidents and current dag run status:running
[2024-10-14T08:59:09.856+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T08:59:09.863+0000] {base.py:84} INFO - Retrieving connection 'spark'
[2024-10-14T08:59:09.864+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark-submit --master local[*]:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py
[2024-10-14T08:59:11.436+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkContext: Running Spark version 3.5.3
[2024-10-14T08:59:11.437+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkContext: OS info Linux, 6.6.32-linuxkit, aarch64
[2024-10-14T08:59:11.438+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkContext: Java version 17.0.12
[2024-10-14T08:59:11.468+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-14T08:59:11.511+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO ResourceUtils: ==============================================================
[2024-10-14T08:59:11.512+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-14T08:59:11.512+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO ResourceUtils: ==============================================================
[2024-10-14T08:59:11.512+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkContext: Submitted application: CountAccidents
[2024-10-14T08:59:11.522+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-14T08:59:11.526+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO ResourceProfile: Limiting resource is cpu
[2024-10-14T08:59:11.527+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-14T08:59:11.552+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SecurityManager: Changing view acls to: default
[2024-10-14T08:59:11.553+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SecurityManager: Changing modify acls to: default
[2024-10-14T08:59:11.553+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SecurityManager: Changing view acls groups to:
[2024-10-14T08:59:11.554+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SecurityManager: Changing modify acls groups to:
[2024-10-14T08:59:11.554+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2024-10-14T08:59:11.670+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO Utils: Successfully started service 'sparkDriver' on port 44803.
[2024-10-14T08:59:11.683+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkEnv: Registering MapOutputTracker
[2024-10-14T08:59:11.702+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-14T08:59:11.710+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-14T08:59:11.711+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-14T08:59:11.713+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-14T08:59:11.724+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-2b6cc706-071a-4c61-a851-0a29f8b2bb57
[2024-10-14T08:59:11.731+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-14T08:59:11.738+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-14T08:59:11.796+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-14T08:59:11.836+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-14T08:59:11.862+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 ERROR SparkContext: Error initializing SparkContext.
[2024-10-14T08:59:11.863+0000] {spark_submit.py:571} INFO - org.apache.spark.SparkException: Could not parse Master URL: 'spark-submit --master local[*]:7077'
[2024-10-14T08:59:11.863+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:3194)
[2024-10-14T08:59:11.863+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:577)
[2024-10-14T08:59:11.864+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-10-14T08:59:11.864+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-10-14T08:59:11.864+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-10-14T08:59:11.864+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-10-14T08:59:11.865+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2024-10-14T08:59:11.865+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2024-10-14T08:59:11.865+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-10-14T08:59:11.866+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-10-14T08:59:11.866+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2024-10-14T08:59:11.866+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-10-14T08:59:11.866+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-10-14T08:59:11.866+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-14T08:59:11.867+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-14T08:59:11.867+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T08:59:11.867+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-14T08:59:11.869+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkUI: Stopped Spark web UI at http://14eb9bd36bc1:4040
[2024-10-14T08:59:11.882+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-14T08:59:11.890+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO MemoryStore: MemoryStore cleared
[2024-10-14T08:59:11.891+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO BlockManager: BlockManager stopped
[2024-10-14T08:59:11.894+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-14T08:59:11.894+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 WARN MetricsSystem: Stopping a MetricsSystem that is not running
[2024-10-14T08:59:11.895+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-14T08:59:11.900+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO SparkContext: Successfully stopped SparkContext
[2024-10-14T08:59:11.900+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-10-14T08:59:11.901+0000] {spark_submit.py:571} INFO - File "/opt/airflow/spark/count_accidents.py", line 19, in <module>
[2024-10-14T08:59:11.901+0000] {spark_submit.py:571} INFO - count_accidents()
[2024-10-14T08:59:11.901+0000] {spark_submit.py:571} INFO - File "/opt/airflow/spark/count_accidents.py", line 8, in count_accidents
[2024-10-14T08:59:11.902+0000] {spark_submit.py:571} INFO - spark = SparkSession.builder.appName("CountAccidents").getOrCreate()
[2024-10-14T08:59:11.902+0000] {spark_submit.py:571} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-14T08:59:11.902+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 497, in getOrCreate
[2024-10-14T08:59:11.902+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 515, in getOrCreate
[2024-10-14T08:59:11.903+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 203, in __init__
[2024-10-14T08:59:11.903+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 296, in _do_init
[2024-10-14T08:59:11.903+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 421, in _initialize_context
[2024-10-14T08:59:11.904+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1587, in __call__
[2024-10-14T08:59:11.904+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-10-14T08:59:11.904+0000] {spark_submit.py:571} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2024-10-14T08:59:11.904+0000] {spark_submit.py:571} INFO - : org.apache.spark.SparkException: Could not parse Master URL: 'spark-submit --master local[*]:7077'
[2024-10-14T08:59:11.904+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:3194)
[2024-10-14T08:59:11.904+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:577)
[2024-10-14T08:59:11.905+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-10-14T08:59:11.905+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-10-14T08:59:11.905+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-10-14T08:59:11.905+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-10-14T08:59:11.905+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2024-10-14T08:59:11.905+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2024-10-14T08:59:11.906+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-10-14T08:59:11.906+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-10-14T08:59:11.906+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2024-10-14T08:59:11.906+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-10-14T08:59:11.906+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-10-14T08:59:11.906+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-14T08:59:11.906+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-14T08:59:11.906+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T08:59:11.906+0000] {spark_submit.py:571} INFO - 
[2024-10-14T08:59:11.927+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO ShutdownHookManager: Shutdown hook called
[2024-10-14T08:59:11.928+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-36441257-06dc-4550-b3dd-5522259ddbaa
[2024-10-14T08:59:11.929+0000] {spark_submit.py:571} INFO - 24/10/14 08:59:11 INFO ShutdownHookManager: Deleting directory /tmp/spark-167fb41d-9097-411b-80aa-41f9bc4686ba
[2024-10-14T08:59:11.953+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-submit --master local[*]:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.
[2024-10-14T08:59:11.955+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-14T08:59:11.956+0000] {logging_mixin.py:190} INFO - Task start:2024-10-14 08:59:09.736071+00:00 end:2024-10-14 08:59:11.955710+00:00 duration:2.219639
[2024-10-14T08:59:11.956+0000] {logging_mixin.py:190} INFO - Task:<Task(SparkSubmitOperator): spark_count_number_of_accidents> dag:<DAG: count_accidents> dagrun:<DagRun count_accidents @ 2024-10-14 08:59:08.221057+00:00: manual__2024-10-14T08:59:08.221057+00:00, state:running, queued_at: 2024-10-14 08:59:08.233708+00:00. externally triggered: True>
[2024-10-14T08:59:11.956+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot execute: spark-submit --master spark-submit --master local[*]:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.
[2024-10-14T08:59:11.956+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=count_accidents, task_id=spark_count_number_of_accidents, run_id=manual__2024-10-14T08:59:08.221057+00:00, execution_date=20241014T085908, start_date=20241014T085909, end_date=20241014T085911
[2024-10-14T08:59:11.966+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T08:59:11.966+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 328 for task spark_count_number_of_accidents (Cannot execute: spark-submit --master spark-submit --master local[*]:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.; 1585)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-submit --master local[*]:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.
[2024-10-14T08:59:11.996+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T08:59:12.009+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T08:59:12.010+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
