[2024-10-14T09:00:37.758+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T09:00:37.771+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T09:00:36.238917+00:00 [queued]>
[2024-10-14T09:00:37.776+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T09:00:36.238917+00:00 [queued]>
[2024-10-14T09:00:37.776+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-14T09:00:37.783+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): spark_count_number_of_accidents> on 2024-10-14 09:00:36.238917+00:00
[2024-10-14T09:00:37.786+0000] {warnings.py:112} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1734) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-14T09:00:37.787+0000] {standard_task_runner.py:72} INFO - Started process 1736 to run task
[2024-10-14T09:00:37.789+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'count_accidents', 'spark_count_number_of_accidents', 'manual__2024-10-14T09:00:36.238917+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/count_accidents_dag.py', '--cfg-path', '/tmp/tmpc4k4xg7x']
[2024-10-14T09:00:37.789+0000] {standard_task_runner.py:105} INFO - Job 329: Subtask spark_count_number_of_accidents
[2024-10-14T09:00:37.827+0000] {task_command.py:467} INFO - Running <TaskInstance: count_accidents.spark_count_number_of_accidents manual__2024-10-14T09:00:36.238917+00:00 [running]> on host 14eb9bd36bc1
[2024-10-14T09:00:37.880+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='count_accidents' AIRFLOW_CTX_TASK_ID='spark_count_number_of_accidents' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T09:00:36.238917+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-14T09:00:36.238917+00:00'
[2024-10-14T09:00:37.881+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T09:00:37.881+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T09:00:37.882+0000] {logging_mixin.py:190} INFO - Current task name:spark_count_number_of_accidents state:running start_date:2024-10-14 09:00:37.771978+00:00
[2024-10-14T09:00:37.882+0000] {logging_mixin.py:190} INFO - Dag name:count_accidents and current dag run status:running
[2024-10-14T09:00:37.882+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T09:00:37.887+0000] {base.py:84} INFO - Retrieving connection 'spark'
[2024-10-14T09:00:37.889+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark-submit --master local[*] --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py
[2024-10-14T09:00:39.449+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkContext: Running Spark version 3.5.3
[2024-10-14T09:00:39.450+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkContext: OS info Linux, 6.6.32-linuxkit, aarch64
[2024-10-14T09:00:39.451+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkContext: Java version 17.0.12
[2024-10-14T09:00:39.482+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-14T09:00:39.529+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO ResourceUtils: ==============================================================
[2024-10-14T09:00:39.530+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-14T09:00:39.530+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO ResourceUtils: ==============================================================
[2024-10-14T09:00:39.530+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkContext: Submitted application: CountAccidents
[2024-10-14T09:00:39.540+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-14T09:00:39.545+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO ResourceProfile: Limiting resource is cpu
[2024-10-14T09:00:39.545+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-14T09:00:39.569+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SecurityManager: Changing view acls to: default
[2024-10-14T09:00:39.569+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SecurityManager: Changing modify acls to: default
[2024-10-14T09:00:39.569+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SecurityManager: Changing view acls groups to:
[2024-10-14T09:00:39.570+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SecurityManager: Changing modify acls groups to:
[2024-10-14T09:00:39.570+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2024-10-14T09:00:39.678+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO Utils: Successfully started service 'sparkDriver' on port 41107.
[2024-10-14T09:00:39.692+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkEnv: Registering MapOutputTracker
[2024-10-14T09:00:39.710+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-14T09:00:39.719+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-14T09:00:39.719+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-14T09:00:39.721+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-14T09:00:39.732+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0cc6a3af-a69a-4cd4-abcb-877f99ef60d4
[2024-10-14T09:00:39.739+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-14T09:00:39.747+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-14T09:00:39.802+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-14T09:00:39.848+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-14T09:00:39.875+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 ERROR SparkContext: Error initializing SparkContext.
[2024-10-14T09:00:39.875+0000] {spark_submit.py:571} INFO - org.apache.spark.SparkException: Could not parse Master URL: 'spark-submit --master local[*] --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py:7077'
[2024-10-14T09:00:39.875+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:3194)
[2024-10-14T09:00:39.876+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:577)
[2024-10-14T09:00:39.876+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-10-14T09:00:39.877+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-10-14T09:00:39.878+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-10-14T09:00:39.878+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-10-14T09:00:39.878+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2024-10-14T09:00:39.879+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2024-10-14T09:00:39.879+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-10-14T09:00:39.879+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-10-14T09:00:39.879+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2024-10-14T09:00:39.879+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-10-14T09:00:39.879+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-10-14T09:00:39.880+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-14T09:00:39.880+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-14T09:00:39.880+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:00:39.880+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-14T09:00:39.881+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkUI: Stopped Spark web UI at http://14eb9bd36bc1:4040
[2024-10-14T09:00:39.901+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-14T09:00:39.907+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO MemoryStore: MemoryStore cleared
[2024-10-14T09:00:39.908+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO BlockManager: BlockManager stopped
[2024-10-14T09:00:39.911+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-14T09:00:39.911+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 WARN MetricsSystem: Stopping a MetricsSystem that is not running
[2024-10-14T09:00:39.912+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-14T09:00:39.917+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO SparkContext: Successfully stopped SparkContext
[2024-10-14T09:00:39.918+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-10-14T09:00:39.918+0000] {spark_submit.py:571} INFO - File "/opt/airflow/spark/count_accidents.py", line 19, in <module>
[2024-10-14T09:00:39.918+0000] {spark_submit.py:571} INFO - count_accidents()
[2024-10-14T09:00:39.919+0000] {spark_submit.py:571} INFO - File "/opt/airflow/spark/count_accidents.py", line 8, in count_accidents
[2024-10-14T09:00:39.919+0000] {spark_submit.py:571} INFO - spark = SparkSession.builder.appName("CountAccidents").getOrCreate()
[2024-10-14T09:00:39.919+0000] {spark_submit.py:571} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-14T09:00:39.919+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 497, in getOrCreate
[2024-10-14T09:00:39.920+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 515, in getOrCreate
[2024-10-14T09:00:39.920+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 203, in __init__
[2024-10-14T09:00:39.920+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 296, in _do_init
[2024-10-14T09:00:39.920+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 421, in _initialize_context
[2024-10-14T09:00:39.921+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1587, in __call__
[2024-10-14T09:00:39.921+0000] {spark_submit.py:571} INFO - File "/home/airflow/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-10-14T09:00:39.921+0000] {spark_submit.py:571} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2024-10-14T09:00:39.921+0000] {spark_submit.py:571} INFO - : org.apache.spark.SparkException: Could not parse Master URL: 'spark-submit --master local[*] --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py:7077'
[2024-10-14T09:00:39.922+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:3194)
[2024-10-14T09:00:39.922+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:577)
[2024-10-14T09:00:39.922+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-10-14T09:00:39.922+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-10-14T09:00:39.922+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-10-14T09:00:39.923+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-10-14T09:00:39.923+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2024-10-14T09:00:39.923+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2024-10-14T09:00:39.923+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-10-14T09:00:39.923+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-10-14T09:00:39.923+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2024-10-14T09:00:39.923+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-10-14T09:00:39.924+0000] {spark_submit.py:571} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-10-14T09:00:39.924+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-10-14T09:00:39.924+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-10-14T09:00:39.924+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-14T09:00:39.924+0000] {spark_submit.py:571} INFO - 
[2024-10-14T09:00:39.948+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO ShutdownHookManager: Shutdown hook called
[2024-10-14T09:00:39.948+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-6d0c3578-970f-4487-91c7-8b6533ad3221
[2024-10-14T09:00:39.950+0000] {spark_submit.py:571} INFO - 24/10/14 09:00:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-8c61c2db-d759-47c7-8b48-d8980d2ffbeb
[2024-10-14T09:00:39.975+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-submit --master local[*] --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.
[2024-10-14T09:00:39.978+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-14T09:00:39.979+0000] {logging_mixin.py:190} INFO - Task start:2024-10-14 09:00:37.771978+00:00 end:2024-10-14 09:00:39.978299+00:00 duration:2.206321
[2024-10-14T09:00:39.979+0000] {logging_mixin.py:190} INFO - Task:<Task(SparkSubmitOperator): spark_count_number_of_accidents> dag:<DAG: count_accidents> dagrun:<DagRun count_accidents @ 2024-10-14 09:00:36.238917+00:00: manual__2024-10-14T09:00:36.238917+00:00, state:running, queued_at: 2024-10-14 09:00:36.251133+00:00. externally triggered: True>
[2024-10-14T09:00:39.979+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot execute: spark-submit --master spark-submit --master local[*] --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.
[2024-10-14T09:00:39.979+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=count_accidents, task_id=spark_count_number_of_accidents, run_id=manual__2024-10-14T09:00:36.238917+00:00, execution_date=20241014T090036, start_date=20241014T090037, end_date=20241014T090039
[2024-10-14T09:00:39.988+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T09:00:39.989+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 329 for task spark_count_number_of_accidents (Cannot execute: spark-submit --master spark-submit --master local[*] --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.; 1736)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-submit --master local[*] --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py:7077 --name arrow-spark --queue YARN --deploy-mode client ./spark/count_accidents.py. Error code is: 1.
[2024-10-14T09:00:40.026+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T09:00:40.039+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T09:00:40.039+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
